name = "videovault-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "videovault-proxy-prod"
vars = { }

routes = [
  {
    pattern = "videoproxy.*.workers.dev",
    zone_name = ""
  }
]

[build]
command = ""
cwd = "."
